# Generated by Django 5.2 on 2026-02-28 15:42

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
